orbs:
  gcp-cli: circleci/gcp-cli@2.1.0
  gcp-gcr: circleci/gcp-gcr@0.13.0
version: 2.1
workflows:
  install_and_configure_cli:
    jobs:
      - gcp-cli/install_and_initialize_cli:
          context: my-context1
          executor: gcp-cli/default
      - build-and-push:
          context: my-context1
          image: backend-image
          registry-url: us.gcr.io
          source-tag: mytag1
          target-tag: mytag2
      